export type ArticleSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type ArticleImage = {
  src: string;
  alt: string;
  caption: string;
};

export type SeoArticle = {
  slug: string;
  title: string;
  titleZh: string;
  description: string;
  descriptionZh: string;
  category: string;
  published: string;
  updated: string;
  readingTime: string;
  primaryKeyword: string;
  images?: ArticleImage[];
  sections: ArticleSection[];
};

export const SEO_ARTICLES: SeoArticle[] = [
  {
    slug: "summer-wool-linen-silk-trousers",
    title: "Wool, Linen and Silk Trousers for Summer Tailoring",
    titleZh: "夏季毛麻丝西裤：轻盈面料与定制细节展示",
    description: "A close look at grey wool-linen-silk trousers designed for warm-weather tailoring, with a clean back pocket and adjustable waistband details.",
    descriptionZh: "灰色毛麻丝夏季西裤成品展示，重点呈现轻盈表面、后袋、腰头与侧调节细节。",
    category: "Finished Garment",
    published: "2026-06-18",
    updated: "2026-06-18",
    readingTime: "4 min read",
    primaryKeyword: "wool linen silk trousers",
    images: [
      { src: "/news/summer-wool-linen-silk-trousers/grey-summer-trousers-full-view.webp", alt: "Grey wool linen silk summer trousers shown on a hanger", caption: "The completed grey trousers show a restrained surface texture and a clean tailored silhouette for summer wardrobes." },
      { src: "/news/summer-wool-linen-silk-trousers/grey-trousers-side-adjuster-detail.webp", alt: "Side adjuster and back pocket detail on grey summer trousers", caption: "The side adjuster, rear welt pocket and waistband finishing give the trousers a precise tailored character without relying on a belt." },
    ],
    sections: [
      { heading: "A summer trouser built around material balance", paragraphs: ["Wool, linen and silk trousers bring together three fibres with different roles. In this finished grey pair, the objective is not to make an exaggerated statement but to create a refined warm-weather trouser with visible texture, controlled drape and a polished appearance.", "For tailoring stores, a blended summer cloth can offer a useful alternative between crisp pure linen and conventional business suiting. The exact performance still depends on the selected cloth weight, weave and composition, so those specifications should be confirmed for each order."] },
      { heading: "Tailored details that remain visually quiet", paragraphs: ["The back welt pocket, button closure and side adjustment are integrated into a clean waistband. These details let the fabric remain the main visual feature while giving the wearer a practical way to refine the fit at the waist.", "The images document the completed garment and its external construction. They do not replace a technical specification: waistband height, rise, pleat choice, hem and pocket treatment should still be written into the approved order before production."] },
      { heading: "How stores can specify a summer trouser", paragraphs: ["A useful order brief should identify the fabric reference, intended climate, preferred rise, waistband system, pocket layout and finished hem. Retailers can then connect the material story to decisions that customers can see and feel, rather than relying on broad claims such as lightweight or luxurious.", "For repeat orders, save the accepted finished measurements and the exact cloth reference together. This makes it easier to reproduce the balance of comfort, drape and appearance in a later pair."] },
    ],
  },
  {
    slug: "customer-fit-tailored-trousers",
    title: "Tailored Trousers on the Customer: Fit and Silhouette Review",
    titleZh: "西裤客户上身效果：腰位、褶量与裤型观察",
    description: "Three customer-fit views showing how high-rise pleated trousers and side adjusters influence balance, ease and leg line.",
    descriptionZh: "通过三张客户上身图，展示高腰、前褶、侧调节袢以及不同裤型的实际轮廓。",
    category: "Fit Review",
    published: "2026-05-28",
    updated: "2026-05-28",
    readingTime: "5 min read",
    primaryKeyword: "tailored trousers fit",
    images: [
      { src: "/news/customer-fit-tailored-trousers/grey-pleated-trousers-customer-fit.webp", alt: "Customer wearing grey high-rise pleated tailored trousers", caption: "The grey pair combines a higher waist, extended closure and front pleats with a relaxed straight leg." },
      { src: "/news/customer-fit-tailored-trousers/navy-pinstripe-trousers-customer-fit.webp", alt: "Customer wearing navy pinstripe pleated trousers", caption: "The navy pinstripe pair shows how a darker cloth and vertical stripe reinforce the long line of the trouser." },
      { src: "/news/customer-fit-tailored-trousers/blue-grey-trousers-front-fit.webp", alt: "Front fit of blue grey high-rise trousers with side adjusters", caption: "A front view makes the waistband position, pleat opening and balance through the leg easier to evaluate." },
    ],
    sections: [
      { heading: "Fit is read from the whole silhouette", paragraphs: ["A trouser can look neat when folded and still behave differently on the body. These customer-fit images show why waist position, seat allowance, front rise, pleat direction and leg width must be considered together. The grey and navy examples use related tailored details but create different visual effects through cloth, stripe and proportion.", "The photographs are useful evidence of overall balance. Final fit decisions should still be based on measurements and the customer's comfort feedback, not on a single camera angle."] },
      { heading: "What the front pleats are doing", paragraphs: ["Pleats provide controlled room at the front of the trouser and can help the cloth fall cleanly from a higher waistband. Their success depends on sufficient rise and seat allowance. If the upper block is too tight, pleats may pull open; if it is too loose, the front can lose definition.", "Side adjusters keep the waistband visually clean and allow small fit changes. They are not a substitute for correct sizing, but they can fine-tune the waist without interrupting the line with a belt."] },
      { heading: "How a retailer should review a fitting", paragraphs: ["Review the waistband level, front closure, pleat behaviour, pocket opening, side seam, back balance and hem at the same time. Ask the wearer to stand naturally and walk before approving the result. A static pose can hide tension or excess cloth that becomes visible in movement.", "Fit feedback should be recorded against the exact order and measurement version. That turns these observations into useful data for the next pair rather than leaving them as informal comments."] },
    ],
  },
  {
    slug: "unstructured-unlined-canvas-jacket",
    title: "An Unstructured, Unlined Jacket with Full Canvas Construction",
    titleZh: "平驳领无结构西装：无里布与全麻无粘衬工艺",
    description: "A grey checked custom jacket combining notch lapels, an unlined interior, natural shoulders and full-canvas construction without fusible interlining.",
    descriptionZh: "灰色格纹定制上衣采用平驳领、自然肩、贴袋、无里布与全麻无粘衬结构。",
    category: "Craftsmanship",
    published: "2025-10-16",
    updated: "2025-10-16",
    readingTime: "5 min read",
    primaryKeyword: "custom tailored suits",
    images: [
      { src: "/news/unstructured-unlined-canvas-jacket/grey-check-unstructured-jacket-front.webp", alt: "Grey checked unstructured custom jacket with notch lapels", caption: "The completed jacket uses notch lapels, patch pockets and a softly defined front." },
      { src: "/news/unstructured-unlined-canvas-jacket/notch-lapel-and-patch-pocket-detail.webp", alt: "Notch lapel and patch pocket on an unlined checked jacket", caption: "A closer view of the lapel, chest area and patch pocket shows the relaxed construction language." },
      { src: "/news/unstructured-unlined-canvas-jacket/natural-shoulder-unlined-jacket-side.webp", alt: "Natural shoulder profile on an unstructured unlined jacket", caption: "The side view highlights the natural shoulder and the restrained amount of internal build-up." },
    ],
    sections: [
      { heading: "Soft appearance does not mean no construction", paragraphs: ["This grey checked jacket was specified with notch lapels, an unstructured expression, no full lining and a full-canvas front without fusible interlining. The result is visually relaxed, but it still requires careful internal control to support the lapel and front edge.", "For custom tailored suits, terms such as unstructured, unlined and full canvas must be recorded separately. They describe different decisions and should not be treated as interchangeable labels."] },
      { heading: "Why the exterior details suit the concept", paragraphs: ["Patch pockets and a natural shoulder reinforce the lighter character of the jacket. The checked cloth remains prominent, while the lapel and front retain enough definition to read as tailoring rather than an overshirt.", "Pattern matching, edge control and pressing become especially visible on an unlined garment because there is less internal material to conceal the construction. The inside should therefore be discussed and approved as part of the design."] },
      { heading: "Specification points for an unlined order", paragraphs: ["A retailer should confirm shoulder treatment, canvas extent, seam finishing, internal pockets, sleeve lining, vent construction and label placement. Full canvas without fusible interlining is a specific production request and should appear clearly on the PI or technical sheet.", "The final choice should match climate, cloth and the customer's expectations. A soft jacket can be comfortable and expressive, but it is not automatically suitable for every fabric or use case."] },
    ],
  },
  {
    slug: "lp-fabric-suit-hanging-shipping-box",
    title: "How a Full-Lined LP Fabric Suit Is Packed for Dispatch",
    titleZh: "LP 面料全衬西装发货：立体挂装包装展示",
    description: "A factory dispatch view of a blue pinstripe full-lined suit secured on a hanger inside a structured garment shipping box.",
    descriptionZh: "蓝色条纹 LP 面料全衬西装采用衣架固定与立体纸箱挂装方式，减少运输中的折叠。",
    category: "Shipping",
    published: "2025-11-20",
    updated: "2025-11-20",
    readingTime: "4 min read",
    primaryKeyword: "custom suits",
    images: [
      { src: "/news/lp-fabric-suit-hanging-shipping-box/blue-pinstripe-suit-hanging-shipping-box.webp", alt: "Blue pinstripe full-lined custom suit in a hanging shipping box", caption: "The finished suit is supported on a hanger inside a structured carton before final closure and dispatch." },
    ],
    sections: [
      { heading: "Packaging is part of the finished product", paragraphs: ["This blue pinstripe suit in LP fabric was completed with a full lining and prepared for dispatch in a structured hanging box. The jacket remains on its hanger rather than being tightly folded into a flat parcel, helping the garment retain its shape during handling.", "The photograph records the packaging style at the factory. Final protection, outer closure and carrier labels still need to follow the destination and shipping method."] },
      { heading: "Why a hanging carton is useful", paragraphs: ["A tailored jacket contains shaped areas at the shoulder, chest and lapel. Reducing hard folds can lower the amount of pressing needed when the order reaches the store. The carton also keeps the garment position more predictable than loose packing.", "Packaging cannot eliminate every transit risk. Moisture protection, internal movement, carton strength and carrier handling remain important, especially for international routes."] },
      { heading: "What retailers should confirm before shipping", paragraphs: ["The order record should connect the garment, customer, destination, package count and tracking number. Retailers should also agree whether suits travel individually, as a consolidated store shipment or with additional branded packaging.", "On receipt, photograph the carton if there is visible damage, inspect the garment before customer delivery and allow time for light steaming or pressing where required."] },
    ],
  },
  {
    slug: "neapolitan-linen-summer-shorts",
    title: "Neapolitan Linen Shorts for a Tailored Summer Wardrobe",
    titleZh: "夏季那不勒斯亚麻短裤：双褶与侧调节细节",
    description: "Striped linen shorts in two colourways with double pleats, extended waistbands, side adjusters and turned cuffs.",
    descriptionZh: "两种条纹配色的那不勒斯风格亚麻短裤，展示双褶、延长腰头、侧调节袢与翻边裤脚。",
    category: "Summer Tailoring",
    published: "2026-06-05",
    updated: "2026-06-05",
    readingTime: "5 min read",
    primaryKeyword: "men's linen shorts",
    images: [
      { src: "/news/neapolitan-linen-summer-shorts/striped-linen-shorts-two-colourways.webp", alt: "Two colourways of striped Neapolitan linen shorts", caption: "Beige and blue striped versions show how the same tailored specification can support different summer palettes." },
      { src: "/news/neapolitan-linen-summer-shorts/beige-striped-linen-shorts-inner-waist.webp", alt: "Interior waistband and extended closure on beige striped linen shorts", caption: "The opened waistband shows the extended closure, internal finishing and front pleat construction." },
      { src: "/news/neapolitan-linen-summer-shorts/blue-striped-linen-shorts-back-detail.webp", alt: "Back pocket and side adjuster on blue striped linen shorts", caption: "The blue colourway combines a rear welt pocket, button closure and metal side adjuster." },
    ],
    sections: [
      { heading: "Shorts treated as tailoring", paragraphs: ["These men's linen shorts use the vocabulary of tailored trousers rather than casual sportswear. Double pleats, an extended waistband, side adjusters, rear welt pockets and turned cuffs create a composed shape while preserving the relaxed purpose of a summer garment.", "The two striped cloths demonstrate how proportion and construction can remain consistent while colour changes the character of the finished piece."] },
      { heading: "The waistband carries much of the design", paragraphs: ["The extended front closure creates a clean line across the waist, while side adjusters reduce the need for a belt. Inside, the waistband and fastening components should be finished to remain comfortable against lightweight summer clothing.", "Pleats add room through the front and help the cloth fall away from the body. Their depth and direction should be specified together with rise and hip allowance."] },
      { heading: "Ordering linen shorts for a collection", paragraphs: ["For a retail programme, confirm fabric weight, transparency, stripe direction, pocketing, waistband style, finished inseam and cuff depth. Linen naturally develops character in wear, so product descriptions should set realistic expectations rather than promising a permanently crease-free surface.", "A small run in coordinated colourways can extend a tailoring offer into summer without abandoning the construction details customers already recognise."] },
    ],
  },
  {
    slug: "cmt-handmade-trousers-premium-trims",
    title: "CMT Handmade Trousers with Premium Trims: A 25-Day Production Case",
    titleZh: "手工西裤来料加工：25 天工期与高规格辅料配置",
    description: "A CMT handmade trouser case using a Riri zip, cotton herringbone pocketing, shirt-cloth waistband, premium buttons and plated side adjusters.",
    descriptionZh: "手工西裤来料加工案例，记录 25 天工期以及 Riri 拉链、全棉鱼纹布、高支衬衫布腰里等辅料。",
    category: "CMT Production",
    published: "2026-04-24",
    updated: "2026-04-24",
    readingTime: "6 min read",
    primaryKeyword: "CMT handmade trousers",
    images: [
      { src: "/news/cmt-handmade-trousers-premium-trims/riri-metal-zip-trouser-detail.webp", alt: "Riri metal zip installed in handmade grey trousers", caption: "The metal zip is one of several customer-specified components documented for this CMT trouser order." },
      { src: "/news/cmt-handmade-trousers-premium-trims/grey-handmade-trousers-back-view.webp", alt: "Grey handmade trousers with rear pocket and side adjuster", caption: "The completed back view shows the rear welt pocket, button and plated waist adjuster." },
      { src: "/news/cmt-handmade-trousers-premium-trims/shirt-fabric-waistband-and-pocketing.webp", alt: "High-count striped shirt cloth used inside a trouser waistband", caption: "The inner waistband uses high-count shirt cloth, paired with cotton pocketing and the specified fastening system." },
      { src: "/news/cmt-handmade-trousers-premium-trims/handmade-trouser-back-pocket-details.webp", alt: "Back pocket finishing on two grey handmade trousers", caption: "A paired view helps check pocket alignment, button placement and consistency between garments." },
    ],
    sections: [
      { heading: "CMT begins with a complete material responsibility list", paragraphs: ["This handmade trouser project was handled as a customer-material CMT order with a stated 25-day production period. The specification included a Riri zip, all-cotton herringbone pocketing, high-count shirting at the waistband, shell or horn buttons, plated metal side adjusters, a YKK trouser hook and Bemberg cupro lining.", "The 25-day period describes this production case, not a universal promise. Timing should be reconfirmed after materials, quantities and technical details are complete."] },
      { heading: "Premium components need production control", paragraphs: ["Named trims matter only when the correct items are received, identified and installed in the approved positions. The factory record should distinguish customer-supplied cloth, factory-supplied components and any approved substitutes.", "Photographs of the zip, waistband, adjuster and pockets create a useful pre-dispatch record, while the PI or technical sheet remains the formal source of truth."] },
      { heading: "How to approve a repeatable trouser standard", paragraphs: ["Before bulk work begins, confirm a representative sample with the final waistband, pocketing, buttons, hooks and adjusters. Measure the agreed control points and record visible workmanship standards such as welt width, button placement and seam appearance.", "For repeat orders, keep component codes and accepted garment measurements together. This prevents a premium trim list from becoming disconnected from the fit and construction it was intended to support."] },
    ],
  },
  {
    slug: "linen-trousers-italian-store-order",
    title: "A Batch of Linen Trousers Made for an Italian Retail Store",
    titleZh: "为意大利门店制作的一批亚麻长裤",
    description: "A production batch of neutral-colour linen trousers prepared for an Italian retail client, with varied colours and finishing details.",
    descriptionZh: "为意大利门店客户制作的亚麻长裤批次，包含米白、浅灰、奶油色、浅棕与条纹款。",
    category: "Retail Order",
    published: "2026-05-15",
    updated: "2026-05-15",
    readingTime: "5 min read",
    primaryKeyword: "linen trousers for men",
    images: [
      { src: "/news/linen-trousers-italian-store-order/italian-store-linen-trousers-production.webp", alt: "Batch of neutral linen trousers made for an Italian retail store", caption: "The store order brings together several light neutral tones and one striped option within a coordinated summer assortment." },
      { src: "/news/linen-trousers-italian-store-order/neutral-linen-trousers-batch.webp", alt: "Cream grey and beige linen trousers hanging after production", caption: "Hanging the completed trousers together supports a visual check of colour range, length and overall consistency before dispatch." },
    ],
    sections: [
      { heading: "A coordinated order rather than one repeated colour", paragraphs: ["This batch of linen trousers was produced for an Italian retail store. The assortment includes cream, off-white, light grey, beige and striped options, allowing the store to present a summer palette while maintaining a related product language.", "For B2B production, variation should be planned rather than improvised. Each colour and style needs its own fabric reference and approved specification even when the garments belong to one collection."] },
      { heading: "What can be checked at batch level", paragraphs: ["A hanging review makes it easier to compare overall length, colour grouping, cloth appearance and visible finishing. It can also reveal whether pieces have been mixed between customer orders before packing.", "Detailed quality control still happens garment by garment. Waist measurements, pocket construction, closures and customer-specific options cannot be approved from a group photograph alone."] },
      { heading: "Planning linen trousers for a retail season", paragraphs: ["Retailers should work backward from the intended selling window and allow time for cloth confirmation, production, international transport and store preparation. Linen demand is seasonal, so late approval can reduce the useful selling period even when sewing is completed correctly.", "Saving accepted specifications by colourway makes reorders more reliable and helps the store expand successful tones without rebuilding the programme from memory."] },
    ],
  },
  {
    slug: "tailored-trouser-construction-details",
    title: "Tailored Trouser Details: Fabric, Waistband, Pockets and Hem",
    titleZh: "长裤西裤细节展示：面料、腰头、口袋与裤脚",
    description: "A detailed view of blue-grey tailored trousers, including cloth texture, extended waistband, zip fly, side adjuster, back pocket and hem.",
    descriptionZh: "蓝灰色定制西裤细节展示，覆盖面料纹理、延长腰头、拉链门襟、侧调节袢、后袋与裤脚。",
    category: "Detail Review",
    published: "2026-06-26",
    updated: "2026-06-26",
    readingTime: "5 min read",
    primaryKeyword: "tailored trouser details",
    images: [
      { src: "/news/tailored-trouser-construction-details/blue-grey-trouser-fabric-texture.webp", alt: "Close-up texture of blue-grey tailored trouser fabric", caption: "The close-up records the fine surface and edge finishing of the blue-grey cloth." },
      { src: "/news/tailored-trouser-construction-details/extended-waistband-and-zip-detail.webp", alt: "Extended waistband zip fly and inner waist on blue-grey trousers", caption: "The opened front shows the extended closure, zip fly, internal waistband and fastening details." },
      { src: "/news/tailored-trouser-construction-details/blue-grey-trousers-complete-view.webp", alt: "Complete blue-grey trousers with side adjuster and plain hem", caption: "A full view connects the waistband, rear pocket, leg line and finished hem." },
      { src: "/news/tailored-trouser-construction-details/single-button-back-pocket-detail.webp", alt: "Single-button rear welt pocket on tailored trousers", caption: "The rear welt pocket uses a narrow button tab and aligned stitching for a restrained finish." },
    ],
    sections: [
      { heading: "Start with the cloth and edge quality", paragraphs: ["Close-up photographs show details that disappear in a full-garment image: yarn texture, seam edges, pressing and the way folded layers meet. This blue-grey cloth has a fine, understated surface that supports a clean tailored presentation.", "A photograph cannot establish fibre content or weight, so those facts should come from the fabric record rather than visual guesswork."] },
      { heading: "The waistband is a system", paragraphs: ["The extended waistband, internal closure, zip fly and side adjustment work together. Their spacing affects comfort and appearance, while the internal materials influence how the waist keeps its shape through wear.", "For production approval, specify waistband height, extension length, hook position, adjuster finish and internal cloth. Small changes in any one item can alter the final balance."] },
      { heading: "Pockets and hems complete the inspection", paragraphs: ["The rear welt pocket should be checked for level placement, consistent width, secure buttoning and clean ends. At the leg opening, the chosen hem must match the order and sit evenly on both legs.", "A useful detail set combines one full-garment image with focused views of the cloth, waistband and pockets. This creates better evidence for retailers than a group of similar beauty shots."] },
    ],
  },
  {
    slug: "neapolitan-double-pleat-trousers",
    title: "Neapolitan Double-Pleat Trousers: A Construction Detail Study",
    titleZh: "那不勒斯双褶西裤：从褶量到内腰的细节展示",
    description: "Beige Neapolitan-style trousers with double pleats, a broad waistband, extended fastening, side pocket and clean internal finishing.",
    descriptionZh: "米灰色那不勒斯风格双褶西裤，展示加宽腰头、延长扣袢、侧袋、后袋与内部结构。",
    category: "Detail Review",
    published: "2026-05-08",
    updated: "2026-05-08",
    readingTime: "5 min read",
    primaryKeyword: "Neapolitan pleated trousers",
    images: [
      { src: "/news/neapolitan-double-pleat-trousers/beige-double-pleat-trousers-full-view.webp", alt: "Beige Neapolitan double-pleat trousers with broad waistband", caption: "The full view shows the double pleats, broad waistband, rear pocket and straight tailored leg." },
      { src: "/news/neapolitan-double-pleat-trousers/beige-trouser-fabric-and-seam-detail.webp", alt: "Close-up of beige trouser fabric and folded seam edges", caption: "A macro view records the cloth texture and the consistency of folded and stitched edges." },
      { src: "/news/neapolitan-double-pleat-trousers/double-pleat-and-side-pocket-detail.webp", alt: "Double pleats and side pocket on beige Neapolitan trousers", caption: "The double pleats open from the broad waistband beside a cleanly finished side pocket." },
      { src: "/news/neapolitan-double-pleat-trousers/extended-waist-tab-and-inner-finish.webp", alt: "Extended waist tab and interior finishing on beige trousers", caption: "The opened waist shows the long adjustment tab, zip, pocketing and internal waistband treatment." },
    ],
    sections: [
      { heading: "The Neapolitan influence is expressed through ease", paragraphs: ["These beige trousers use a broad waistband and double pleats to create room and visual rhythm through the upper block. The result is tailored but not rigid, with the pleats helping the leg fall cleanly below the waist.", "The supplied Chinese fabric name requires confirmation before any brand attribution, so this article describes only the construction and visible cloth characteristics."] },
      { heading: "Pleats, pockets and cloth must work together", paragraphs: ["The double pleats need enough rise and hip allowance to remain composed. Beside them, the side pocket opening is kept narrow and clean so that it does not compete with the front structure.", "The close-up views also show why cloth choice matters. A fabric must accept folding, pressing and seam construction without losing the intended soft appearance."] },
      { heading: "Inside finishing supports the outside line", paragraphs: ["The extended waist tab, zip fly, pocketing and internal waistband are part of the fit system. Their materials and positions affect comfort, fastening security and how the waist sits when worn.", "Retailers should approve these internal choices with the same care as the visible pleats. A complete trouser specification includes both the photographed exterior and the hidden construction that supports it."] },
    ],
  },
  {
    slug: "handmade-flannel-trousers-premium-trims",
    title: "Handmade Flannel Trousers with Riri Zip and Premium Internal Trims",
    titleZh: "手工法兰绒西裤：Riri 拉链与高规格内部辅料",
    description: "Grey handmade flannel trousers shown inside and out, with double pleats, side adjusters, striped waistband cloth and premium specified trims.",
    descriptionZh: "灰色手工法兰绒西裤内外细节展示，包含双褶、侧调节扣、条纹腰里与指定高规格辅料。",
    category: "CMT Production",
    published: "2025-12-11",
    updated: "2025-12-11",
    readingTime: "6 min read",
    primaryKeyword: "handmade flannel trousers",
    images: [
      { src: "/news/handmade-flannel-trousers-premium-trims/grey-flannel-trousers-back-view.webp", alt: "Grey handmade flannel trousers with rear pocket and cuffed hem", caption: "The completed back view shows the soft flannel surface, rear pocket, side adjuster and cuffed hem." },
      { src: "/news/handmade-flannel-trousers-premium-trims/grey-flannel-front-pleat-adjuster.webp", alt: "Front pleat and black side adjuster on grey flannel trousers", caption: "A close view highlights the front pleat, shaped waistband and dark plated adjustment buckle." },
      { src: "/news/handmade-flannel-trousers-premium-trims/grey-flannel-trousers-inner-construction.webp", alt: "Interior construction of grey flannel trousers with metal zip", caption: "The opened garment documents the zip fly, waistband extension, pocketing and internal construction." },
      { src: "/news/handmade-flannel-trousers-premium-trims/striped-waistband-riri-zip-interior.webp", alt: "Striped shirt-cloth waistband and metal zip inside handmade trousers", caption: "Striped high-count shirt cloth gives the inner waistband a clean, distinctive finish beside the specified metal zip." },
    ],
    sections: [
      { heading: "A second CMT example with a different visual focus", paragraphs: ["This handmade trouser order uses the same premium component standard recorded for the CMT programme: Riri zip, all-cotton herringbone pocketing, high-count shirting at the waist, shell or horn buttons, plated adjusters, YKK trouser hook and Bemberg cupro lining. The stated production period for the order was 25 days.", "Here the grey flannel cloth changes the emphasis. Its soft surface makes pressing, pleat definition and edge control especially visible."] },
      { heading: "The exterior combines softness with structure", paragraphs: ["Double pleats create room through the front, while the shaped waistband and side adjusters keep the upper block controlled. At the back, a single-button welt pocket provides a restrained finish. The cuffed hem adds visual weight at the bottom of the leg.", "Because flannel can mark under aggressive handling, pressing and packaging should preserve the surface rather than flattening it excessively."] },
      { heading: "Internal trims are documented, not hidden", paragraphs: ["The interior images show the striped waistband cloth, zip, closures and pocketing as a connected system. This is useful for store clients who need confidence that specified components are present rather than relying only on an external beauty shot.", "For future production, component brands and material descriptions should remain attached to the approved sample record. The 25-day timing should be reconfirmed for each quantity and material delivery schedule."] },
    ],
  },
  {
    slug: "150-custom-linen-trousers-bulk-order-completed",
    title: "150 Custom Linen Trousers Completed for a Bulk Order",
    titleZh: "150 条定制亚麻西裤团单保质保量完成",
    description: "A 150-piece custom linen trouser order completed with consistent construction, elasticated comfort waistbands and carefully finished details.",
    descriptionZh: "150 条定制亚麻西裤团单已保质保量完成，展示成衣版型、松紧抽绳腰头、拉链与批量生产细节。",
    category: "Workshop Update",
    published: "2026-08-27",
    updated: "2026-08-27",
    readingTime: "3 min read",
    primaryKeyword: "custom linen trousers manufacturer",
    images: [
      { src: "/news/custom-linen-trousers-150/custom-linen-trousers-blue-and-beige.webp", alt: "Blue and beige custom linen trousers with elasticated drawstring waistbands", caption: "Two colourways from the completed custom linen trouser order, showing the tailored front and comfort waistband construction." },
      { src: "/news/custom-linen-trousers-150/bulk-linen-trousers-production.webp", alt: "Completed beige linen trousers stacked after bulk production", caption: "Completed trousers prepared together after production, with consistent waist and drawstring details across the order." },
      { src: "/news/custom-linen-trousers-150/linen-trouser-metal-zip-detail.webp", alt: "Metal zip and clean interior finishing on custom linen trousers", caption: "Close-up of the metal zip and interior seam finishing used on the custom trousers." },
    ],
    sections: [
      { heading: "A 150-piece custom trouser order completed", paragraphs: ["Our workshop has completed a bulk order of 150 custom linen trousers. The order combines a tailored appearance with practical comfort details, making the trousers suitable for warm-weather uniforms, hospitality teams, retail collections and private-label programmes.", "The finished garments were organised and checked as a complete production batch so that colour, construction and visible finishing remained consistent across the order."] },
      { heading: "Tailored structure with an adjustable comfort waist", paragraphs: ["The trousers feature a clean tailored front together with an elasticated back waistband and drawstring adjustment. This construction gives the garment a smarter appearance than casual drawstring trousers while allowing more flexibility for daily wear.", "Blue and natural beige colourways demonstrate how the same specification can be adapted for different uniform or collection requirements."], bullets: ["Tailored trouser front with belt loops", "Elasticated back waist for additional comfort", "Drawstring adjustment", "Metal zip fastening and clean interior finishing", "Repeatable construction for coordinated bulk orders"] },
      { heading: "Quality and quantity controlled together", paragraphs: ["Bulk custom production is not only about reaching the requested quantity. It also requires the approved garment details to be repeated consistently. For this order, the waistband gathering, drawstrings, fastening components and visible seams were treated as shared control points throughout production.", "For tailoring shops, uniform buyers and menswear brands, we can develop custom trousers around the required fabric, colour, sizing plan and construction specification. Enquiries can begin with a reference sample, technical notes or clear product photographs."] },
    ],
  },
  {
    slug: "vbc-super-150s-full-canvas-three-piece-suit",
    title: "Completed Custom VBC 150s Full-Canvas Three-Piece Suit",
    titleZh: "定制成品展示：VBC 150s 全麻无粘衬三件套",
    description: "A workshop look at a completed custom VBC 150s full-canvas three-piece suit, including its clean peak lapels, balanced front and non-fused construction.",
    descriptionZh: "本期定制成品采用 VBC 150s 面料与全麻无粘衬结构，展示戗驳领、前身平衡和高级三件套西装的制作重点。",
    category: "Workshop Update",
    published: "2026-08-27",
    updated: "2026-08-27",
    readingTime: "6 min read",
    primaryKeyword: "custom VBC 150s full canvas three-piece suit",
    images: [
      { src: "/news/vbc-super-150s-full-canvas-three-piece-suit/vbc-super-150s-custom-suit-jacket-front.webp", alt: "Front view of a grey custom VBC 150s full-canvas suit jacket with peak lapels", caption: "Completed jacket front: a restrained grey cloth, peak lapels and a clean, balanced presentation." },
      { src: "/news/vbc-super-150s-full-canvas-three-piece-suit/vbc-super-150s-full-canvas-suit-lapel-detail.webp", alt: "Close-up of peak lapel and chest on a custom VBC 150s full-canvas suit", caption: "Close-up of the lapel, chest and cloth surface under natural light." },
    ],
    sections: [
      { heading: "A completed VBC 150s three-piece suit from our workshop", paragraphs: ["This completed custom order is a grey three-piece suit made with VBC 150s cloth and a full-canvas, non-fused construction. The set comprises a jacket, waistcoat and trousers, giving the wearer a coordinated option for business, formal occasions and other settings where a more complete tailored presentation is required.", "The photographs focus on the jacket because its front balance, lapel line and chest are the clearest places to assess the character of the tailoring. The restrained grey tone makes the suit versatile, while the subtle surface texture becomes more visible in natural light. Rather than relying on decorative details, the design uses proportion and a clean silhouette to create a polished result."] },
      { heading: "Why choose a full-canvas, non-fused construction?", paragraphs: ["A full-canvas suit uses a floating internal canvas through the front of the jacket instead of bonding the outer cloth to a fusible interlining. The purpose is not simply to add a premium label. The internal structure supports the chest and lapel while allowing the outer fabric to retain a more natural appearance.", "For tailoring businesses sourcing a custom full-canvas three-piece suit, construction must be specified clearly at the order stage. Fabric choice, canvas structure, measurements and style details work as one system; selecting an expensive cloth alone cannot correct an incomplete specification or an unsuitable pattern. Our production review therefore confirms the construction together with the approved garment details before cutting begins."], bullets: ["Full canvas through the jacket front", "No fused front interlining", "Coordinated jacket, waistcoat and trousers", "Order-specific measurements and style selections"] },
      { heading: "Peak lapels and a disciplined front design", paragraphs: ["Peak lapels give this custom VBC 150s suit a more assertive formal line. Their points extend toward the shoulders, visually strengthening the upper body without requiring excessive width. The buttonhole, welt chest pocket and flap pockets are kept understated so that the lapel shape and cloth remain the main visual features.", "The front also shows the practical value of careful pressing and alignment. Pocket positions, lapel edges and the two sides of the jacket need to read as a single composition. These details matter to made-to-measure suit retailers because clients often judge a finished garment first from its overall balance and only later from its internal construction."] },
      { heading: "VBC 150s cloth requires controlled tailoring", paragraphs: ["Fine suit cloth rewards precise handling. During production, the goal is to preserve a smooth surface while building enough structure for the intended silhouette. Cutting, shaping, sewing and pressing must be coordinated so that the finished garment looks clean without appearing rigid.", "For a VBC fabric custom suit order, the exact bunch and article reference should always be recorded separately from the general fabric description. This protects repeat-order accuracy and helps the retailer confirm availability before promising a delivery date. The same discipline applies to lining, buttons, lapel style, pockets and all customer-specific measurements."] },
      { heading: "What B2B tailoring partners can specify", paragraphs: ["We work with tailoring shops, menswear retailers and private-label businesses that need order-level customization rather than a fixed ready-to-wear product. A full-canvas made-to-measure suit can be developed around the store's customer profile, measurement method and preferred style language, subject to fabric and production confirmation.", "When requesting a similar three-piece suit, provide the fabric reference, body and garment measurements, posture notes, jacket construction, lapel and pocket choices, waistcoat design, trouser details, lining, buttons and required delivery destination. A complete specification enables a more accurate review, quotation and production schedule. It also creates a reliable record for future alterations or reorders.", "This finished VBC 150s full-canvas three-piece suit illustrates our approach: clarify the order, control the construction and let proportion, cloth and workmanship produce the final impression. For wholesale, private-label or one-piece made-to-measure enquiries, send us your target product, fabric preference and order requirements for a project-specific assessment."] },
    ],
  },
  {
    slug: "choose-private-label-suit-manufacturer",
    title: "How to Choose a Private-Label Suit Manufacturer",
    titleZh: "如何选择可靠的西服私牌生产商",
    description: "A practical evaluation framework for tailoring shops and menswear retailers comparing private-label suit manufacturers.",
    descriptionZh: "为裁缝店与男装零售商整理的私牌西服生产商评估方法。",
    category: "Supplier Guide",
    published: "2026-08-24",
    updated: "2026-08-24",
    readingTime: "7 min read",
    primaryKeyword: "private label suit manufacturer",
    sections: [
      { heading: "Start with the operating model, not the sample", paragraphs: ["A polished sample proves that a factory can make one good garment. It does not prove that the factory can repeat the result across different customers, body shapes and reorder dates. Ask how measurements, style choices, fabric codes, pattern adjustments and quality notes are stored. A reliable private-label partner should be able to explain the full order path from enquiry to after-sales support."], bullets: ["Confirm whether your store name appears on customer-facing documents.", "Ask who owns measurement records and order history.", "Check whether one-piece reorders follow the same process as first orders."] },
      { heading: "Test communication with a real order", paragraphs: ["Before committing to a large launch, place a representative order that includes a normal level of complexity. Review the PI, requested measurements, selected fabric and construction details line by line. The quality of clarification before production is often a better predictor of a durable partnership than a low headline price."], bullets: ["Request written confirmation of price, lead time and shipping scope.", "Use one fabric code and one complete style specification.", "Record every correction and check whether it appears in the final order summary."] },
      { heading: "Evaluate repeatability and transparency", paragraphs: ["The best B2B relationship is one in which your team can see what was ordered, why it costs what it costs and what will happen next. Compare suppliers on consistency, traceability and response quality, not only unit price. A manufacturer that prevents one remake can be more valuable than one offering a small initial discount."] },
    ],
  },
  {
    slug: "made-to-measure-suit-ordering-process",
    title: "The B2B Made-to-Measure Suit Ordering Process, Step by Step",
    titleZh: "B2B 量身定制西服下单流程详解",
    description: "From client measurements and fabric selection to PI approval, production, QC, shipping and reorders.",
    descriptionZh: "从量体、选料到 PI 确认、生产质检、发货与复购的完整流程。",
    category: "Ordering Process",
    published: "2026-08-23",
    updated: "2026-08-24",
    readingTime: "8 min read",
    primaryKeyword: "made to measure suit ordering process",
    sections: [
      { heading: "1. Create a complete customer record", paragraphs: ["The order begins with customer identity, height, weight, body measurements, finished-garment measurements where available and posture notes. The record should distinguish body measurements from garment measurements so that ease is intentional rather than guessed."] },
      { heading: "2. Select fabric and style", paragraphs: ["Record the fabric bunch and article code together. Then select garment type, front fastening, lapel, pockets, vents, lining, buttons and optional craft details. Images are useful, but the PI should also contain text labels that remain understandable when images are unavailable."] },
      { heading: "3. Review and approve the PI", paragraphs: ["The proforma invoice is the commercial and technical checkpoint. Verify the customer, fabric code, garment quantity, style summary, price, shipping address and payment terms. Production should start only after discrepancies are corrected and approval is recorded."] },
      { heading: "4. Production, QC and delivery", paragraphs: ["During production, the manufacturer translates the approved record into patterns and garments. Quality control should cover measurements, symmetry, construction, fabric identity and visible finish. After dispatch, keep the tracking record with the order. Once the customer receives the garment, save fit feedback for the next reorder."] },
    ],
  },
  {
    slug: "low-moq-custom-suit-manufacturing",
    title: "Low-MOQ Custom Suit Manufacturing: What One-Piece Ordering Requires",
    titleZh: "低起订量西服定制：一件起订真正需要什么",
    description: "What retailers should verify before relying on a one-piece MOQ custom suit supplier.",
    descriptionZh: "零售商选择一件起订西服供应商前需要确认的关键事项。",
    category: "Business Model",
    published: "2026-08-22",
    updated: "2026-08-24",
    readingTime: "6 min read",
    primaryKeyword: "low MOQ custom suit manufacturer",
    sections: [
      { heading: "One-piece MOQ is a workflow, not a slogan", paragraphs: ["A factory can support one-piece orders only when fabric identification, measurement input, pattern changes, pricing and production status are controlled at order level. Without this infrastructure, small orders are easily delayed or mixed with other work."] },
      { heading: "Check the commercial boundaries", paragraphs: ["Ask whether the MOQ applies to every fabric, every garment and every destination. Confirm sample surcharges, fabric-only minimums, remake policies and freight. One-piece availability does not automatically mean bulk pricing or unlimited customization."], bullets: ["Minimum quantity by garment type", "Available fabric bunches", "Base making price and paid options", "Shipping method and destination charges"] },
      { heading: "Use low MOQ to learn before scaling", paragraphs: ["For a new store or collection, low MOQ reduces inventory risk and creates a controlled way to test fit, service and customer demand. Track corrections carefully. When repeat orders become predictable, negotiate production planning based on actual volume rather than forecasts."] },
    ],
  },
  {
    slug: "white-label-vs-private-label-tailoring",
    title: "White Label vs Private Label Tailoring: Which Model Fits Your Store?",
    titleZh: "白牌与私牌西服定制：哪种模式适合你的门店",
    description: "A clear comparison of white-label and private-label made-to-measure supply models.",
    descriptionZh: "清晰比较白牌与私牌量身定制供应模式。",
    category: "Business Model",
    published: "2026-08-21",
    updated: "2026-08-24",
    readingTime: "6 min read",
    primaryKeyword: "white label tailoring",
    sections: [
      { heading: "White label: speed and operational simplicity", paragraphs: ["White-label supply usually uses a manufacturer’s established product and operating system while allowing the retailer to sell under its own customer relationship. It suits stores that want to launch quickly without designing every production standard from the beginning."] },
      { heading: "Private label: greater brand control", paragraphs: ["Private-label programs may add custom labels, packaging, product rules, exclusive options or a more deeply branded ordering experience. The trade-off is additional setup, approvals and responsibility for consistent specifications."] },
      { heading: "Choose based on what the customer can see", paragraphs: ["List every customer-facing touchpoint: website, fitting, PI, garment label, packaging, shipping notification and after-sales message. Decide which elements must carry your brand and which can remain operational. A staged approach often works best: begin with a proven white-label workflow, then add private-label elements after order volume and service standards are stable."] },
    ],
  },
  {
    slug: "italian-fabric-sourcing-for-tailors",
    title: "Italian Suit Fabric Sourcing for Tailors: Bunches, Codes and Reorders",
    titleZh: "裁缝店采购意大利西服面料：面料册、编号与复购",
    description: "How tailoring businesses can manage Italian fabric bunches, article codes, availability and customer expectations.",
    descriptionZh: "如何管理意大利面料册、货号、库存与客户预期。",
    category: "Fabric Sourcing",
    published: "2026-08-20",
    updated: "2026-08-24",
    readingTime: "7 min read",
    primaryKeyword: "Italian suit fabric supplier for tailors",
    sections: [
      { heading: "The bunch number and article number serve different jobs", paragraphs: ["The bunch identifies the collection; the article identifies the specific cloth. Save them together, for example 6402·33731, so staff can return to the right visual reference and the supplier can confirm the exact article. Color names alone are not reliable identifiers."] },
      { heading: "Translate specifications into customer value", paragraphs: ["Composition, weight, weave and season help a tailor explain performance. Weight influences drape and climate suitability, while construction and fiber blend affect handle, resilience and care. Avoid promising universal performance from one specification; describe the intended use and confirm unusual requirements with the supplier."] },
      { heading: "Treat availability as order-specific", paragraphs: ["A bunch can remain in your library after individual articles sell out. Confirm availability before taking payment and again when a delayed order is released. For repeat customers, store the original code and an approved alternative process rather than substituting silently."] },
    ],
  },
  {
    slug: "digital-measurement-records-reorders",
    title: "Why Digital Measurement Records Improve Made-to-Measure Reorders",
    titleZh: "数字化量体档案如何提升定制西服复购",
    description: "A practical data model for customer measurements, posture, fit feedback and repeat orders.",
    descriptionZh: "客户量体、体态、试穿反馈与复购数据的实用管理方法。",
    category: "Retail Operations",
    published: "2026-08-19",
    updated: "2026-08-24",
    readingTime: "6 min read",
    primaryKeyword: "made to measure measurement records",
    sections: [
      { heading: "A measurement is meaningful only with context", paragraphs: ["Store the unit system, measurement type, garment category, date and person who recorded it. Body measurements and finished-garment measurements must remain separate. Posture observations and fit preferences should be structured fields rather than hidden inside free-form notes."] },
      { heading: "Never overwrite history", paragraphs: ["When a customer changes weight or requests a fit correction, create a new dated version. The previous record explains what changed and protects the store from repeating an old mistake. Link every order to the measurement version used at approval time."] },
      { heading: "Turn delivery feedback into the next order", paragraphs: ["After delivery, record whether the customer accepted the fit, requested alteration or changed preference. A reorder should begin from the last accepted garment, not simply the newest numbers. This makes repeat service faster while keeping the final decision visible to staff."] },
    ],
  },
  {
    slug: "custom-suit-production-lead-time",
    title: "Custom Suit Production Lead Times: What Retailers Should Plan For",
    titleZh: "定制西服生产周期：零售门店应如何规划",
    description: "A realistic guide to fabric confirmation, production, QC, shipping and event-date planning.",
    descriptionZh: "从面料确认、生产质检到运输与活动日期的实际规划指南。",
    category: "Delivery Planning",
    published: "2026-08-18",
    updated: "2026-08-24",
    readingTime: "6 min read",
    primaryKeyword: "custom suit production lead time",
    sections: [
      { heading: "Lead time starts after the order is complete", paragraphs: ["An enquiry date is not a production start date. The clock should begin after fabric availability, measurements, style, price and payment conditions are confirmed. Missing details create queues that are often mistaken for slow sewing."] },
      { heading: "Separate production time from transit time", paragraphs: ["Quote the customer using distinct stages: order review, fabric allocation, production, quality control, international transport and local alteration buffer. Customs and carrier schedules vary by route, so do not represent an estimate as a guarantee."] },
      { heading: "Work backward from the wearing date", paragraphs: ["For weddings, events and seasonal launches, include time for a first fitting and correction. If the available window is too short, reduce complexity or decline the deadline. A transparent no is better than an unverified promise that damages the retailer’s customer relationship."] },
    ],
  },
  {
    slug: "made-to-measure-quality-control-checklist",
    title: "Made-to-Measure Suit Quality Control: A Retailer’s Checklist",
    titleZh: "量身定制西服质检：零售门店检查清单",
    description: "A repeatable receiving and pre-delivery inspection checklist for made-to-measure garments.",
    descriptionZh: "适用于量身定制服装收货与交付前检查的标准清单。",
    category: "Quality Control",
    published: "2026-08-17",
    updated: "2026-08-24",
    readingTime: "7 min read",
    primaryKeyword: "made to measure suit quality control",
    sections: [
      { heading: "Verify identity before workmanship", paragraphs: ["First confirm customer, garment type, fabric code, lining, buttons and monogram. A beautifully made garment in the wrong cloth is still a failed order. Keep the approved PI available during inspection."] },
      { heading: "Inspect construction systematically", paragraphs: ["Check symmetry, seam appearance, lapel roll, pocket alignment, button security, lining attachment, pressing and visible marks. Measure the agreed control points using the same method used during ordering. Small tolerances may be normal, but the supplier and retailer should agree how they are assessed."], bullets: ["Correct fabric and trims", "Key finished measurements", "Left-right symmetry", "Clean finish and pressing", "Customer-specific details"] },
      { heading: "Classify issues before responding", paragraphs: ["Separate manufacturing defects, measurement discrepancies, customer preference changes and transit damage. Photograph the full garment, the affected area and the measurement method. Clear evidence helps the supplier choose an alteration, remake or other resolution quickly."] },
    ],
  },
  {
    slug: "international-shipping-custom-suits",
    title: "International Shipping for B2B Custom Suits: A Practical Guide",
    titleZh: "B2B 定制西服国际运输实用指南",
    description: "How tailoring shops can plan addresses, documents, tracking, duties and delivery evidence.",
    descriptionZh: "门店如何规划地址、单据、追踪、税费与签收证据。",
    category: "Shipping",
    published: "2026-08-16",
    updated: "2026-08-24",
    readingTime: "6 min read",
    primaryKeyword: "international shipping custom suits",
    sections: [
      { heading: "Make the address machine-readable", paragraphs: ["Store country using the recognized ISO code and keep state or province, city, postal code, street and contact phone in separate fields. Confirm scripts and transliterations required by the carrier. A complete address reduces manual correction and failed delivery risk."] },
      { heading: "Define responsibility before dispatch", paragraphs: ["The PI should state the shipping method and clarify who is responsible for import duties, taxes and local fees. These charges depend on destination and import arrangement; confirm them with the carrier, customs broker or local authority rather than relying on a generic website estimate."] },
      { heading: "Keep proof connected to the order", paragraphs: ["Save the tracking number, dispatch date, package count and delivery status with the PI. When a customer reports a problem, the store can see what was shipped and when. Delivery photos or signed proof should be published as marketing evidence only with permission and private details removed."] },
    ],
  },
  {
    slug: "start-private-label-suit-line",
    title: "How to Start a Private-Label Suit Line Without Building a Factory",
    titleZh: "不自建工厂，如何启动私牌西服业务",
    description: "A staged launch plan for menswear boutiques, tailoring shops and new made-to-measure brands.",
    descriptionZh: "适用于男装精品店、裁缝店与新定制品牌的分阶段启动方案。",
    category: "Launch Guide",
    published: "2026-08-15",
    updated: "2026-08-24",
    readingTime: "8 min read",
    primaryKeyword: "start a private label suit line",
    sections: [
      { heading: "Define a narrow first offer", paragraphs: ["Start with a clear customer, price position and small set of garments. A focused launch—such as business suits and separate trousers—makes training, sample investment and quality control manageable. Add complex options after staff can order the core range consistently."] },
      { heading: "Build the service before the advertising", paragraphs: ["Create a repeatable appointment, measurement, style consultation, PI approval, payment and after-sales process. Train staff using the same forms customers will encounter. Your brand promise must match the manufacturer’s actual lead times and correction policy."] },
      { heading: "Launch with evidence, not claims", paragraphs: ["Document anonymized order checkpoints, quality inspections, tracking and delivered garments with client permission. Explain what each image proves. A transparent process page is more credible than generic statements such as ‘premium quality’ because buyers can see how decisions and responsibilities move from the store to production and back."] },
      { heading: "Improve from the first ten orders", paragraphs: ["Review each completed order for data errors, fit corrections, communication delays and customer questions. Turn repeated questions into website guidance and repeated errors into required fields. The result is a private-label operation that becomes easier to scale because learning is captured in the system."] },
    ],
  },
].filter((article) => article.images && article.images.length > 0);

export function getArticle(slug: string) {
  return SEO_ARTICLES.find((article) => article.slug === slug);
}
