import type { Locale } from "./i18n";

const keys = ["landing.navJourney","landing.storyTitle","landing.storyLead","landing.cuttingTitle","landing.cuttingText","landing.qcTitle","landing.qcText","landing.storyQuote","landing.storyLink","landing.advantageTitle","landing.advantage1","landing.advantage1Text","landing.advantage2","landing.advantage2Text","landing.advantage3","landing.advantage3Text","landing.advantage4","landing.advantage4Text","landing.contactSending"] as const;

const values: Partial<Record<Locale, string[]>> = {
  de: ["Kooperationsablauf","Keine Lagerware. Ein Produkt für einen Kunden.","verosuits überführt Maße, Stoff- und Modellauswahl Ihres Geschäfts in einen produktionsreifen Auftrag. Ihre Marke bleibt sichtbar; dahinter arbeitet ein rückverfolgbarer Maßkonfektionsprozess.","Einzelzuschnitt","Stoffcode, Maße und Schnittmuster werden jedem Auftrag eindeutig zugeordnet","Qualitätskontrolle","Reversfall, Symmetrie, Verarbeitung und Erscheinungsbild werden geprüft","Das System sichert Präzision. Das Handwerk verleiht Charakter.","Gesamten Kooperationsablauf ansehen →","Mehr Freiheit für Ihre Kunden. Weniger Aufwand für Ihr Geschäft.","Ab 1 Stück","Sakkos, Hosen, Westen und Hemden können kundenbezogen ohne Fertigwarenlager bestellt werden.","Vier Ebenen der Individualisierung","Stoff, Maße, Körperhaltung und Ausstattungsdetails ergeben einen vollständigen, prüfbaren Auftrag.","White Label für Fachgeschäfte","Ihre Marke bleibt im Kundenkontakt sichtbar, während die Produktion diskret im Hintergrund arbeitet.","Für Nachbestellungen dokumentiert","Datierte Maße, Haltung und Ausstattungsdetails bilden eine verlässliche Grundlage für Folgeaufträge.","Wird gesendet…"],
  ja: ["ご注文の流れ","既製品卸ではなく、お客様一人のための一着。","verosuitsは店舗で採寸した寸法、生地、仕様を工場が確実に生産できる注文へ変換します。お客様には店舗ブランドを見せ、追跡可能なMTM生産が裏側を支えます。","一着ごとの裁断","生地品番、採寸値、型紙を注文ごとに照合","完成品検品","ラペルの返り、左右対称、縫製仕様、外観を確認","デジタル管理が正確さを守り、職人技が風合いを生みます。","ご注文の流れを見る →","お客様には自由を。店舗には簡単な発注を。","1着から発注","ジャケット、トラウザーズ、ウェストコート、シャツを顧客別に発注でき、在庫は不要です。","4領域のカスタマイズ","生地、採寸、体型補正、仕様を一つの確認可能な注文にまとめます。","店舗ブランドのホワイトラベル","顧客対応では店舗ブランドを前面に出し、工場は裏側で生産します。","再注文に使える記録","採寸、体型、仕様と更新日時を保存し、確実な再注文につなげます。","送信中…"],
  fr: ["Parcours de collaboration","Pas de stock de prêt-à-porter. Une pièce créée pour un client.","verosuits transforme les mesures, le tissu et les choix de style de votre boutique en commande prête pour la production. Votre marque reste visible, soutenue par un processus sur mesure traçable.","Coupe à l’unité","Référence tissu, mesures et patron associés à chaque commande","Contrôle qualité du vêtement","Tombé du revers, symétrie, confection et aspect contrôlés","Le système garantit la précision. Le savoir-faire donne du caractère.","Voir tout le parcours →","Plus de liberté pour vos clients. Moins de friction pour votre boutique.","Dès 1 pièce","Vestes, pantalons, gilets et chemises se commandent par client, sans stock de vêtements finis.","Quatre niveaux de personnalisation","Tissu, mesures, posture et finitions forment une commande complète et vérifiable.","Marque blanche pour boutiques","Votre marque reste au premier plan tandis que la production opère discrètement.","Données prêtes pour le réassort","Mesures, posture, finitions et dates créent une base fiable pour les nouvelles commandes.","Envoi…"],
  it: ["Percorso di collaborazione","Non stock di confezione. Un capo creato per un cliente.","verosuits trasforma misure, tessuto e scelte di stile del negozio in un ordine pronto per la produzione. Il cliente vede il vostro marchio, supportato da un processo su misura tracciabile.","Taglio del singolo ordine","Codice tessuto, misure e cartamodello abbinati a ogni ordine","Controllo qualità del capo","Controllo di rollatura del rever, simmetria, lavorazione e aspetto","Il sistema garantisce precisione. L’artigianalità dà carattere.","Vedi l’intero percorso →","Più libertà per il cliente. Meno attriti per il negozio.","Minimo 1 capo","Giacche, pantaloni, gilet e camicie ordinabili per singolo cliente senza scorte di capi finiti.","Quattro livelli di personalizzazione","Tessuto, misure, postura e dettagli formano un ordine completo e verificabile.","White label per il negozio","Il vostro marchio resta in primo piano mentre la produzione opera dietro le quinte.","Dati pronti per il riordino","Misure, postura, dettagli e date creano una base affidabile per i riordini.","Invio…"],
  es: ["Proceso de colaboración","No es stock de confección. Una prenda creada para un cliente.","verosuits convierte las medidas, el tejido y las opciones de estilo de su tienda en un pedido listo para producción. El cliente ve su marca, respaldada por un proceso a medida trazable.","Corte por pedido","Código de tejido, medidas y patrón vinculados a cada pedido","Control de calidad de la prenda","Se revisan caída de solapa, simetría, confección y aspecto","El sistema protege la precisión. La artesanía aporta carácter.","Ver el proceso completo →","Más libertad para el cliente. Menos fricción para la tienda.","Desde 1 prenda","Chaquetas, pantalones, chalecos y camisas por cliente, sin almacenar prendas terminadas.","Cuatro niveles de personalización","Tejido, medidas, postura y acabados forman un pedido completo y verificable.","Marca blanca para la tienda","Su marca permanece ante el cliente mientras la producción trabaja discretamente.","Datos listos para reposición","Medidas, postura, acabados y fechas crean una base fiable para repetir pedidos.","Enviando…"],
  pt: ["Processo de colaboração","Não é stock de pronto-a-vestir. Uma peça criada para um cliente.","A verosuits transforma medidas, tecido e escolhas de modelo da sua loja numa encomenda pronta para produção. O cliente vê a sua marca, apoiada por um processo por medida rastreável.","Corte por encomenda","Código do tecido, medidas e molde associados a cada encomenda","Controlo de qualidade da peça","Verificação da lapela, simetria, confeção e aspeto","O sistema garante precisão. O ofício dá carácter.","Ver todo o processo →","Mais liberdade para o cliente. Menos atrito para a loja.","A partir de 1 peça","Casacos, calças, coletes e camisas por cliente, sem stock de peças acabadas.","Quatro níveis de personalização","Tecido, medidas, postura e acabamentos formam uma encomenda completa e verificável.","Marca branca para a loja","A sua marca permanece visível enquanto a produção trabalha discretamente.","Dados prontos para reposição","Medidas, postura, acabamentos e datas criam uma base fiável para novas encomendas.","A enviar…"],
  nl: ["Samenwerkingsproces","Geen confectievoorraad. Eén kledingstuk voor één klant.","verosuits zet maten, stof en modelkeuzes van uw winkel om in een productierijpe order. Uw klant ziet uw merk, ondersteund door een traceerbaar maatwerkproces.","Knippen per order","Stofcode, maten en patroon worden per order gekoppeld","Kwaliteitscontrole kledingstuk","Reversrol, symmetrie, afwerking en uitstraling worden gecontroleerd","Het systeem bewaakt nauwkeurigheid. Vakmanschap geeft karakter.","Bekijk het volledige proces →","Meer vrijheid voor uw klant. Minder gedoe voor uw winkel.","Vanaf 1 stuk","Jasjes, broeken, gilets en overhemden per klant bestellen zonder voorraad gereed product.","Vier lagen maatwerk","Stof, maten, houding en details vormen één volledige, controleerbare order.","White label voor de winkel","Uw merk blijft zichtbaar; de productie werkt discreet op de achtergrond.","Gegevens voor nabestellingen","Maten, houding, details en datums vormen een betrouwbare basis voor herhaalorders.","Verzenden…"],
  pl: ["Proces współpracy","Nie magazyn odzieży gotowej. Jeden produkt dla jednego klienta.","verosuits przekształca wymiary, tkaninę i wybory fasonu salonu w zamówienie gotowe do produkcji. Klient widzi Państwa markę, wspieraną przez identyfikowalny proces MTM.","Krojenie pojedynczego zamówienia","Kod tkaniny, wymiary i szablon przypisane do każdego zamówienia","Kontrola jakości odzieży","Kontrola układania klap, symetrii, wykonania i wyglądu","System zapewnia dokładność. Rzemiosło nadaje charakter.","Zobacz pełny proces →","Więcej swobody dla klienta. Prostsze zamawianie dla salonu.","Od 1 sztuki","Marynarki, spodnie, kamizelki i koszule na pojedyncze zamówienie bez zapasu gotowej odzieży.","Cztery poziomy personalizacji","Tkanina, wymiary, postawa i detale tworzą kompletne zamówienie do weryfikacji.","White label dla salonu","Państwa marka pozostaje widoczna, a produkcja działa dyskretnie w tle.","Dane gotowe do domówień","Wymiary, postawa, detale i daty tworzą wiarygodną podstawę kolejnych zamówień.","Wysyłanie…"],
  sv: ["Samarbetsprocess","Inget konfektionslager. Ett plagg skapat för en kund.","verosuits omvandlar butikens mått, tyg- och modellval till en produktionsklar order. Kunden ser ert varumärke, med en spårbar måttsydd process bakom.","Klippning per order","Tygkod, mått och mönster kopplas till varje order","Kvalitetskontroll av plagg","Slagets rullning, symmetri, sömnad och utseende kontrolleras","Systemet säkrar precision. Hantverket ger karaktär.","Se hela processen →","Mer frihet för kunden. Mindre friktion för butiken.","Från 1 plagg","Kavajer, byxor, västar och skjortor beställs per kund utan lager av färdiga plagg.","Fyra nivåer av anpassning","Tyg, mått, hållning och detaljer bildar en komplett, verifierbar order.","White label för butiken","Ert varumärke syns för kunden medan produktionen sker diskret i bakgrunden.","Data för återbeställning","Mått, hållning, detaljer och datum ger en säker grund för nya order.","Skickar…"],
  da: ["Samarbejdsforløb","Ikke konfektionslager. Ét produkt skabt til én kunde.","verosuits omsætter butikkens mål, stof- og modelvalg til en produktionsklar ordre. Kunden ser jeres brand, understøttet af en sporbar målsyet proces.","Klipning pr. ordre","Stofkode, mål og mønster knyttes til hver ordre","Kvalitetskontrol af tøjet","Reversrulning, symmetri, udførelse og udseende kontrolleres","Systemet sikrer præcision. Håndværket giver karakter.","Se hele forløbet →","Mere frihed til kunden. Mindre besvær for butikken.","Fra 1 stk.","Jakker, bukser, veste og skjorter bestilles pr. kunde uden lager af færdigvarer.","Fire lag af tilpasning","Stof, mål, kropsholdning og detaljer danner en komplet, kontrollerbar ordre.","White label til butikken","Jeres brand forbliver synligt, mens produktionen foregår diskret.","Data klar til genbestilling","Mål, kropsholdning, detaljer og datoer giver et sikkert grundlag for nye ordrer.","Sender…"],
  no: ["Samarbeidsprosess","Ikke konfeksjonslager. Ett plagg laget for én kunde.","verosuits gjør butikkens mål, stoff- og modellvalg om til en produksjonsklar bestilling. Kunden ser deres merkevare, støttet av en sporbar målsydd prosess.","Klipping per bestilling","Stoffkode, mål og mønster kobles til hver bestilling","Kvalitetskontroll av plagg","Slagets rulling, symmetri, utførelse og utseende kontrolleres","Systemet sikrer presisjon. Håndverket gir karakter.","Se hele prosessen →","Mer frihet for kunden. Mindre friksjon for butikken.","Fra 1 plagg","Jakker, bukser, vester og skjorter bestilles per kunde uten lager av ferdige plagg.","Fire nivåer av tilpasning","Stoff, mål, kroppsholdning og detaljer danner en komplett, kontrollerbar bestilling.","White label for butikken","Deres merkevare forblir synlig mens produksjonen skjer diskret.","Data klare for gjenbestilling","Mål, kroppsholdning, detaljer og datoer gir et pålitelig grunnlag for nye bestillinger.","Sender…"],
  cs: ["Průběh spolupráce","Ne sklad konfekce. Jeden výrobek pro jednoho zákazníka.","verosuits převádí míry, látku a volbu střihu z vaší prodejny do objednávky připravené k výrobě. Zákazník vidí vaši značku, za níž stojí dohledatelný proces zakázkového šití.","Stříhání po jednotlivých zakázkách","Kód látky, míry a střih jsou přiřazeny ke každé objednávce","Kontrola kvality oděvu","Kontroluje se přetočení klopy, souměrnost, zpracování a vzhled","Systém zajišťuje přesnost. Řemeslo dodává charakter.","Zobrazit celý proces →","Více svobody pro zákazníka. Méně komplikací pro prodejnu.","Od 1 kusu","Saka, kalhoty, vesty a košile lze objednávat pro jednotlivé zákazníky bez skladu hotových oděvů.","Čtyři úrovně individualizace","Látka, míry, držení těla a detaily tvoří úplnou, ověřitelnou objednávku.","White label pro prodejnu","Vaše značka zůstává v popředí a výroba probíhá diskrétně v pozadí.","Údaje pro opakované objednávky","Míry, držení těla, detaily a data tvoří spolehlivý základ pro další objednávky.","Odesílání…"],
};

const stats: Partial<Record<Locale, Record<string, string>>> = {
  fr: { "landing.statYears": "Années de confection sur mesure", "landing.statMarkets": "Marchés partenaires", "landing.statLeadValue": "4 semaines", "landing.statLead": "Délai de production standard", "landing.statMills": "Maisons de tissus" },
  it: { "landing.statYears": "Anni di sartoria su misura", "landing.statMarkets": "Mercati partner", "landing.statLeadValue": "4 settimane", "landing.statLead": "Tempo di produzione standard", "landing.statMills": "Lanifici partner" },
  es: { "landing.statYears": "Años de confección a medida", "landing.statMarkets": "Mercados asociados", "landing.statLeadValue": "4 semanas", "landing.statLead": "Plazo de producción estándar", "landing.statMills": "Casas de tejidos" },
  pt: { "landing.statYears": "Anos de confeção por medida", "landing.statMarkets": "Mercados parceiros", "landing.statLeadValue": "4 semanas", "landing.statLead": "Prazo de produção padrão", "landing.statMills": "Fabricantes de tecidos" },
  nl: { "landing.statYears": "Jaar ervaring in maatwerk", "landing.statMarkets": "Partnermarkten", "landing.statLeadValue": "4 weken", "landing.statLead": "Standaard productietijd", "landing.statMills": "Stoffenweverijen" },
  pl: { "landing.statYears": "Lat produkcji miarowej", "landing.statMarkets": "Rynków partnerskich", "landing.statLeadValue": "4 tygodnie", "landing.statLead": "Standardowy czas produkcji", "landing.statMills": "Producentów tkanin" },
  sv: { "landing.statYears": "År av måttsydd produktion", "landing.statMarkets": "Partnermarknader", "landing.statLeadValue": "4 veckor", "landing.statLead": "Standardproduktionstid", "landing.statMills": "Tygväverier" },
  da: { "landing.statYears": "År med målsyet produktion", "landing.statMarkets": "Partnermarkeder", "landing.statLeadValue": "4 uger", "landing.statLead": "Standard produktionstid", "landing.statMills": "Stofvæverier" },
  no: { "landing.statYears": "År med målsydd produksjon", "landing.statMarkets": "Partnermarkeder", "landing.statLeadValue": "4 uker", "landing.statLead": "Standard produksjonstid", "landing.statMills": "Stoffveverier" },
  cs: { "landing.statYears": "Let zakázkové výroby", "landing.statMarkets": "Partnerských trhů", "landing.statLeadValue": "4 týdny", "landing.statLead": "Standardní výrobní lhůta", "landing.statMills": "Tkalcoven látek" },
};

export function homepageTranslation(locale: Locale, key: string): string | undefined {
  const stat = stats[locale]?.[key];
  if (stat) return stat;
  const index = keys.indexOf(key as (typeof keys)[number]);
  return index < 0 ? undefined : values[locale]?.[index];
}
