-- Replace the refunded demo case and expand the store account to a realistic demo portfolio.
DELETE FROM orders WHERE owner_id=2 AND order_no='DEMO-VERO-1008';
DELETE FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-08';

INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Alexander Reed','179 cm','75 kg','DEMO-VERO-21','United Kingdom','England','Manchester','12 King Street','M2 6AN','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-21');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Sebastian Cole','185 cm','83 kg','DEMO-VERO-22','United States','Illinois','Chicago','21 Lake Street','60601','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-22');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Thomas Becker','181 cm','77 kg','DEMO-VERO-23','Germany','Berlin','Berlin','73 Friedrichstrasse','10117','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-23');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Hugo Laurent','177 cm','71 kg','DEMO-VERO-24','France','Occitanie','Lyon','8 Rue Merciere','69002','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-24');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Daniel Rossi','180 cm','78 kg','DEMO-VERO-25','Italy','Lazio','Rome','19 Via del Corso','00186','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-25');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Samuel Brooks','183 cm','80 kg','DEMO-VERO-26','Canada','British Columbia','Vancouver','44 Granville Street','V6C 1T1','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-26');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Adrian Murphy','182 cm','79 kg','DEMO-VERO-27','Ireland','Leinster','Dublin','5 Grafton Street','D02 X285','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-27');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Gabriel Santos','176 cm','74 kg','DEMO-VERO-28','Portugal','Lisbon','Lisbon','10 Rua Augusta','1100-048','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-28');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Victor Andersen','187 cm','87 kg','DEMO-VERO-29','Denmark','Capital Region','Copenhagen','22 Amagertorv','1160','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-29');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Julian Weber','178 cm','73 kg','DEMO-VERO-30','Austria','Vienna','Vienna','16 Kohlmarkt','1010','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-30');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Nathaniel Price','184 cm','82 kg','DEMO-VERO-31','United States','Massachusetts','Boston','61 Beacon Street','02108','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-31');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Oscar Lindberg','181 cm','76 kg','DEMO-VERO-32','Sweden','Stockholm','Stockholm','37 Strandvagen','114 56','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-32');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Leo Fischer','179 cm','74 kg','DEMO-VERO-33','Switzerland','Zurich','Zurich','3 Bahnhofstrasse','8001','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-33');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Maxime Bernard','180 cm','77 kg','DEMO-VERO-34','Belgium','Brussels','Brussels','15 Avenue Louise','1050','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-34');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Ryan O''Connor','186 cm','85 kg','DEMO-VERO-35','Australia','New South Wales','Sydney','26 George Street','2000','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-35');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Marco Bianchi','177 cm','72 kg','DEMO-VERO-36','Italy','Tuscany','Florence','11 Via Roma','50123','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-36');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Theo Martin','183 cm','81 kg','DEMO-VERO-37','France','Provence','Marseille','7 Quai du Port','13002','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-37');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Mason Turner','180 cm','76 kg','DEMO-VERO-38','United States','Texas','Austin','29 Congress Avenue','78701','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-38');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Jonas Eriksen','182 cm','79 kg','DEMO-VERO-39','Norway','Oslo','Oslo','4 Karl Johans gate','0154','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-39');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Adam Kowalski','184 cm','83 kg','DEMO-VERO-40','Poland','Masovian','Warsaw','18 Nowy Swiat','00-373','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-40');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'George Miller','181 cm','78 kg','DEMO-VERO-41','Canada','Quebec','Montreal','28 Saint Paul Street','H2Y 1G3','Demo customer','{}',3,5080,'2026-09-04 18:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-41');

INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at)
SELECT 2,printf('DEMO-VERO-%04d',2000 + c.id * 10 + n.n),c.id,'{}',CASE n.n WHEN 1 THEN 'completed' WHEN 2 THEN 'shipped' ELSE 'production' END,'paid',CASE n.n WHEN 1 THEN 'jacket' WHEN 2 THEN 'trousers' ELSE 'shirt' END,CASE n.n WHEN 1 THEN 'Business Suit Reorder' WHEN 2 THEN 'Pleated Trousers Reorder' ELSE 'Custom Stripe Shirt' END,CASE n.n WHEN 1 THEN 'VBC-110-NV' WHEN 2 THEN 'TR-121-NV' ELSE 'SH-102-ST' END,CASE n.n WHEN 1 THEN 'Navy Wool' WHEN 2 THEN 'Classic Navy' ELSE 'Blue Stripe' END,CASE n.n WHEN 1 THEN 'Vitale Barberis Canonico' WHEN 2 THEN 'House Collection' ELSE 'Albini' END,CASE n.n WHEN 1 THEN 1300 WHEN 2 THEN 1080 ELSE 1550 END,0,CASE n.n WHEN 1 THEN 180 WHEN 2 THEN 120 ELSE 230 END,200,CASE n.n WHEN 1 THEN 1680 WHEN 2 THEN 1400 ELSE 2000 END,'USD',CASE n.n WHEN 1 THEN 1.3 WHEN 2 THEN 0.7 ELSE 0.4 END,'[]','[]','{}',c.channel_code,'2026-09-04 18:00:00','2026-09-04 18:00:00'
FROM customers c CROSS JOIN (SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3) n
WHERE c.owner_id=2 AND c.channel_code LIKE 'DEMO-VERO-2%' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_no=printf('DEMO-VERO-%04d',2000 + c.id * 10 + n.n));
