-- Fictional records for the verosuits store account (owner_id = 2).
-- Re-running is safe: each customer channel code and order number is unique.
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Oliver Bennett','182 cm','78 kg','DEMO-VERO-01','United Kingdom','England','London','14 Wren Street','EC1A 1BB','Demo customer','{}',1,1680,'2026-09-01 09:30:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-01');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'James Whitmore','188 cm','86 kg','DEMO-VERO-02','United States','New York','New York','88 Mercer Street','10012','Demo customer','{}',1,2150,'2026-09-01 14:15:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-02');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Luca Moretti','176 cm','70 kg','DEMO-VERO-03','Italy','Lombardy','Milan','27 Via Torino','20123','Demo customer','{}',1,1320,'2026-09-02 10:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-03');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Felix Schneider','180 cm','76 kg','DEMO-VERO-04','Germany','Bavaria','Munich','9 Prinzregentenstrasse','80538','Demo customer','{}',1,1890,'2026-09-02 16:40:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-04');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Ethan Clarke','184 cm','82 kg','DEMO-VERO-05','Australia','Victoria','Melbourne','31 Collins Street','3000','Demo customer','{}',1,1460,'2026-09-03 08:50:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-05');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Noah Dubois','178 cm','73 kg','DEMO-VERO-06','France','Ile-de-France','Paris','6 Rue de Rivoli','75004','Demo customer','{}',1,1740,'2026-09-03 13:20:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-06');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'William Carter','186 cm','84 kg','DEMO-VERO-07','Canada','Ontario','Toronto','55 King Street West','M5H 1J9','Demo customer','{}',1,2280,'2026-09-04 09:10:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-07');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Mateo Alvarez','175 cm','72 kg','DEMO-VERO-08','Spain','Catalonia','Barcelona','18 Carrer de Mallorca','08029','Demo customer','{}',1,1190,'2026-09-04 11:35:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-08');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Benjamin Foster','181 cm','79 kg','DEMO-VERO-09','United States','California','Los Angeles','210 Spring Street','90012','Demo customer','{}',1,1980,'2026-09-04 15:00:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-09');
INSERT INTO customers (owner_id,name,height,weight,channel_code,country,region,city,street,postal_code,notes,measurements,total_orders,total_spent,last_order_at) SELECT 2,'Henry van Dijk','183 cm','81 kg','DEMO-VERO-10','Netherlands','North Holland','Amsterdam','42 Herengracht','1015 BS','Demo customer','{}',1,1560,'2026-09-04 17:25:00' WHERE NOT EXISTS (SELECT 1 FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-10');

INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1001',id,'{}','confirmed','paid','jacket','Navy Business Suit','VBC-110-NV','Navy Wool','Vitale Barberis Canonico',1280,0,220,180,1680,'USD',1.4,'[]','[]','{}','DEMO-VERO-01','2026-09-01 09:30:00','2026-09-01 09:30:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-01' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1001');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1002',id,'{}','production','paid','jacket','Three-Piece Wedding Suit','34561','Sand Brown','STYLBIELLA',1650,0,300,200,2150,'USD',1.8,'[]','[]','{}','DEMO-VERO-02','2026-09-01 14:15:00','2026-09-01 14:15:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-02' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1002');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1003',id,'{}','shipped','paid','trousers','Pleated Summer Trousers','TR-121-NV','Classic Navy','House Collection',980,0,120,220,1320,'USD',0.7,'[]','[]','{}','DEMO-VERO-03','2026-09-02 10:00:00','2026-09-02 10:00:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-03' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1003');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1004',id,'{}','pending','unpaid','jacket','Charcoal Travel Jacket','34562','Warm Sand Brown','STYLBIELLA',1500,0,190,200,1890,'USD',1.3,'[]','[]','{}','DEMO-VERO-04','2026-09-02 16:40:00','2026-09-02 16:40:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-04' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1004');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1005',id,'{}','completed','paid','shirt','White Formal Shirt','SH-100-WH','Classic White Poplin','Albini',1100,0,120,240,1460,'USD',0.4,'[]','[]','{}','DEMO-VERO-05','2026-09-03 08:50:00','2026-09-03 08:50:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-05' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1005');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1006',id,'{}','confirmed','paid','waistcoat','Ivory Ceremony Waistcoat','WC-CT-IVO','Ivory Ceremony','Ceremony Collection',1350,0,150,240,1740,'USD',0.5,'[]','[]','{}','DEMO-VERO-06','2026-09-03 13:20:00','2026-09-03 13:20:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-06' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1006');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1007',id,'{}','production','paid','jacket','Midnight Blue Tuxedo','VBC-110-NV','Navy Wool','Vitale Barberis Canonico',1850,0,230,200,2280,'USD',1.5,'[]','[]','{}','DEMO-VERO-07','2026-09-04 09:10:00','2026-09-04 09:10:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-07' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1007');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1008',id,'{}','cancelled','refunded','trousers','Linen Blend Trousers','TR-122-MG','Mid Grey Herringbone','House Collection',850,0,120,220,1190,'USD',0.7,'[]','[]','{}','DEMO-VERO-08','2026-09-04 11:35:00','2026-09-04 11:35:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-08' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1008');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1009',id,'{}','shipped','paid','jacket','Brown Check Jacket','34561','Sand Brown','STYLBIELLA',1550,0,230,200,1980,'USD',1.2,'[]','[]','{}','DEMO-VERO-09','2026-09-04 15:00:00','2026-09-04 15:00:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-09' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1009');
INSERT INTO orders (owner_id,order_no,customer_id,customer_snapshot,status,payment_status,garment_type,garment_name,fabric_code,fabric_name,fabric_mill,base_price,fabric_price,option_extra,shipping_fee,total_price,currency,weight_kg,options,measurements,shipping_address,channel_code,created_at,updated_at) SELECT 2,'DEMO-VERO-1010',id,'{}','pending','unpaid','shirt','Blue Stripe Business Shirt','SH-102-ST','Blue Stripe','Albini',1200,0,160,200,1560,'USD',0.4,'[]','[]','{}','DEMO-VERO-10','2026-09-04 17:25:00','2026-09-04 17:25:00' FROM customers WHERE owner_id=2 AND channel_code='DEMO-VERO-10' AND NOT EXISTS (SELECT 1 FROM orders WHERE order_no='DEMO-VERO-1010');
